import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import Swal from 'sweetalert2';
import { CustomerService, Customer } from './customer.service';

@Component({
  selector: 'app-customer-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './customer-form.component.html',
  styleUrls: ['./customer-form.component.css']
})
export class CustomerFormComponent implements OnInit {
  customerForm: Customer = this.getEmptyCustomer();
  isEditMode: boolean = false;
  isLoading: boolean = false;
  
  // Validation errors
  emailError: string = '';
  phoneError: string = '';
  nameArManuallyEdited: boolean = false;

  constructor(
    private customerService: CustomerService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    // Check if editing (customerCode in route params)
    const customerCode = this.route.snapshot.paramMap.get('customerCode');
    if (customerCode) {
      this.isEditMode = true;
      this.loadCustomer(customerCode);
    }
  }

  loadCustomer(customerCode: string): void {
    this.isLoading = true;
    this.customerService.getByCode(customerCode).subscribe({
      next: (customer) => {
        this.customerForm = { ...customer };
        this.isLoading = false;
      },
      error: (err) => {
        this.isLoading = false;
        Swal.fire({
          icon: 'error',
          title: 'Error',
          text: err.message || 'Failed to load customer',
          confirmButtonColor: '#d33'
        });
        this.router.navigate(['./customer']);
      }
    });
  }

  // Handle customer name input change for auto-filling Arabic name
  onCustomerNameChange(value: string): void {
    if (!this.nameArManuallyEdited) {
      this.customerForm.nameAr = this.toArabic(value);
    }
  }

  // Convert English text to Arabic (simple transliteration)
  toArabic(text: string): string {
    const map: { [key: string]: string } = {
      a: 'ا', b: 'ب', t: 'ت', j: 'ج', h: 'ح',
      d: 'د', r: 'ر', s: 'س', f: 'ف',
      k: 'ك', l: 'ل', m: 'م', n: 'ن',
      w: 'و', y: 'ي', e: 'ي', i: 'ي', o: 'و', u: 'و'
    };

    return text
      .toLowerCase()
      .split('')
      .map(c => map[c] || c)
      .join('');
  }

  validateEmail(email: string): boolean {
    if (!email || email.trim() === '') return true; // Optional field
    const regex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
    return regex.test(email);
  }

  validatePhone(phone: string): boolean {
    if (!phone || phone.trim() === '') return true; // Optional field
    return /^[0-9]+$/.test(phone);
  }

  onEmailBlur(): void {
    if (this.customerForm.email && this.customerForm.email.trim() !== '') {
      if (!this.validateEmail(this.customerForm.email)) {
        this.emailError = 'Please enter a valid email address';
      } else {
        this.emailError = '';
      }
    } else {
      this.emailError = '';
    }
  }

  onPhoneBlur(): void {
    if (this.customerForm.phone && this.customerForm.phone.trim() !== '') {
      if (!this.validatePhone(this.customerForm.phone)) {
        this.phoneError = 'Phone number should contain only numbers';
      } else {
        this.phoneError = '';
      }
    } else {
      this.phoneError = '';
    }
  }

  validateForm(): boolean {
    // CustomerCode is now optional - will be auto-generated by backend
    if (!this.customerForm.name || this.customerForm.name.trim() === '') {
      Swal.fire({
        icon: 'warning',
        title: 'Validation Error',
        text: 'Please fill in Customer Name',
        confirmButtonColor: '#3085d6'
      });
      return false;
    }
    if (!this.customerForm.nameAr || this.customerForm.nameAr.trim() === '') {
      Swal.fire({
        icon: 'warning',
        title: 'Validation Error',
        text: 'Please fill in Customer Arabic Name',
        confirmButtonColor: '#3085d6'
      });
      return false;
    }
    // Email and Phone are now optional, only validate if provided
    if (this.emailError) {
      Swal.fire({
        icon: 'warning',
        title: 'Validation Error',
        text: this.emailError,
        confirmButtonColor: '#3085d6'
      });
      return false;
    }
    if (this.phoneError) {
      Swal.fire({
        icon: 'warning',
        title: 'Validation Error',
        text: this.phoneError,
        confirmButtonColor: '#3085d6'
      });
      return false;
    }
    return true;
  }

  saveCustomer(): void {
    if (!this.validateForm()) return;

    this.isLoading = true;

    if (this.isEditMode) {
      this.customerService.update(this.customerForm).subscribe({
        next: () => {
          Swal.fire({
            icon: 'success',
            title: 'Success!',
            text: 'Customer updated successfully',
            confirmButtonColor: '#3085d6',
            timer: 1500
          });
          this.router.navigate(['./customer']);
        },
        error: (err) => {
          this.isLoading = false;
          Swal.fire({
            icon: 'error',
            title: 'Error',
            text: err.message || 'Failed to update customer',
            confirmButtonColor: '#d33'
          });
        }
      });
    } else {
      this.customerService.create(this.customerForm).subscribe({
        next: () => {
          Swal.fire({
            icon: 'success',
            title: 'Success!',
            text: 'Customer created successfully',
            confirmButtonColor: '#3085d6',
            timer: 1500
          });
          this.router.navigate(['./customer']);
        },
        error: (err) => {
          this.isLoading = false;
          Swal.fire({
            icon: 'error',
            title: 'Error',
            text: err.message || 'Failed to create customer',
            confirmButtonColor: '#d33'
          });
        }
      });
    }
  }

  cancel(): void {
    this.router.navigate(['./customer']);
  }

  getEmptyCustomer(): Customer {
    return {
      customerCode: '',
      name: '',
      nameAr: '',
      phone: '',
      email: '',
      address: '',
      vatNo: ''
    };
  }
}
