using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Reflection;
using System.Text.Json.Serialization;

namespace ERP.Api.Swagger;

public class HideAutoGeneratedPropertiesFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        if (schema.Properties == null) return;

        var properties = context.Type.GetProperties();
        foreach (var property in properties)
        {
            // Hide properties marked with JsonIgnore
            var jsonIgnoreAttr = property.GetCustomAttribute<JsonIgnoreAttribute>();
            if (jsonIgnoreAttr != null)
            {
                var propertyName = property.Name;
                // Convert to camelCase for JSON
                var camelCaseName = char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
                
                schema.Properties.Remove(propertyName);
                schema.Properties.Remove(camelCaseName);
            }
        }
    }
}
