using Asp.Versioning;
using Asp.Versioning.ApiExplorer;
using ERP.Api.Auth;
using ERP.Api.Middleware;
using ERP.Application.Abstractions.Logging;
using ERP.Application.Interfaces.Repositories;
using ERP.Application.Interfaces.Services;
using ERP.Application.Services;
using ERP.Domain.Interfaces;
using ERP.Infrastructure.DependencyInjection;
using ERP.Infrastructure.Logging;
using ERP.Infrastructure.Repositories;
using ERP.Repositories.SALES;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
using System;
using System.IO;
using System.Text;

var builder = WebApplication.CreateBuilder(args);
var cfg = builder.Configuration;

// Logging setup
builder.Logging.ClearProviders();
builder.Logging.AddSimpleConsole(o =>
{
    o.IncludeScopes = true;
    o.TimestampFormat = "yyyy-MM-ddTHH:mm:ss.fffZ ";
    o.SingleLine = true;
});

var loggingMode = cfg["Logging:Mode"];
builder.Logging.SetMinimumLevel(
    string.Equals(loggingMode, "Verbose", StringComparison.OrdinalIgnoreCase)
        ? LogLevel.Debug
        : LogLevel.Information);

// Controllers + CORS
builder.Services.AddControllers();

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

builder.Services.AddApiVersioning(options =>
{
    options.DefaultApiVersion = new ApiVersion(1, 0);
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.ReportApiVersions = true;
}).AddApiExplorer(options =>
{
    options.GroupNameFormat = "'v'VVV";
    options.SubstituteApiVersionInUrl = true;
});

// Swagger
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "ERP.Api", Version = "v1" });

    foreach (var xml in Directory.EnumerateFiles(AppContext.BaseDirectory, "*.xml"))
        c.IncludeXmlComments(xml, true);

    // Incoming branch Swagger improvements
    c.UseAllOfToExtendReferenceSchemas();
    c.SupportNonNullableReferenceTypes();
    c.SchemaFilter<ERP.Api.Swagger.HideAutoGeneratedPropertiesFilter>();

    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Enter: Bearer {your token}"
    });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

// Authorization Policies
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("erp.api.read", p =>
        p.RequireAuthenticatedUser().RequireClaim("scope", "erp.api.read"));

    options.AddPolicy("erp.api.write", p =>
        p.RequireAuthenticatedUser().RequireClaim("scope", "erp.api.write"));

    options.AddPolicy("erp.inventory.read", p =>
        p.RequireAuthenticatedUser().RequireClaim("scope", "erp.inventory.read"));

    options.AddPolicy("erp.inventory.write", p =>
        p.RequireAuthenticatedUser().RequireClaim("scope", "erp.inventory.write"));
});

// Services
builder.Services.AddSingleton<IAuthorizationHandler, ScopeAuthorizationHandler>();

builder.Services.AddScoped<IPartsService, PartsService>();
builder.Services.AddScoped<ISuppliersService, SuppliersService>();
builder.Services.AddScoped<ISaasCustomerService, SaasCustomerService>();
builder.Services.AddScoped<IMasterTypesService, MasterTypesService>();
builder.Services.AddScoped<IInventoryLocationsService, InventoryLocationsService>();
builder.Services.AddScoped<IPurchaseOrdersService, PurchaseOrdersService>();
builder.Services.AddScoped<IShipmentsService, ShipmentsService>();
builder.Services.AddScoped<IBranchesService, BranchesService>();
builder.Services.AddScoped<IFranchisesService, FranchisesService>();
builder.Services.AddScoped<ICurrenciesService, CurrenciesService>();
builder.Services.AddScoped<IMakesService, MakesService>();
builder.Services.AddScoped<IStoresService, StoresService>();
builder.Services.AddScoped<IJournalEntriesService, JournalEntriesService>();
builder.Services.AddScoped<IJournalEntryLinesService, JournalEntryLinesService>();
builder.Services.AddScoped<ICustomersService, CustomersService>();
builder.Services.AddScoped<IUsersService, UsersService>();
builder.Services.AddScoped<IWorkshopsService, WorkshopsService>();
builder.Services.AddScoped<IWorkMasterService, WorkMasterService>();
builder.Services.AddScoped<ISalesService, SalesService>();
builder.Services.AddScoped<IReceiptsService, ReceiptsService>();
builder.Services.AddScoped<IShipmentDetailsService, ShipmentDetailsService>();
builder.Services.AddScoped<IPackingService, PackingService>();
builder.Services.AddScoped<ICartonsService, CartonsService>();
builder.Services.AddScoped<IRepairOrderService, RepairOrderService>();

// New modules
builder.Services.AddScoped<IAuthorityService, AuthorityService>();
builder.Services.AddScoped<ICompetitorService, CompetitorService>();
builder.Services.AddScoped<IFinalPartService, FinalPartService>();
builder.Services.AddScoped<ISubsPartService, SubsPartService>();
builder.Services.AddScoped<ICustomerOrdersService, CustomerOrdersService>();
builder.Services.AddScoped<ILoadingAdviceService, LoadingAdviceService>();
builder.Services.AddScoped<IOrderPlanService, OrderPlanService>();
builder.Services.AddScoped<IPriceGroupService, PriceGroupService>();
builder.Services.AddScoped<IPatternCartonService, PatternCartonService>();
builder.Services.AddScoped<IPoAllocationService, PoAllocationService>();
builder.Services.AddScoped<IPoB2BService, PoB2BService>();
builder.Services.AddScoped<IChartOfAccountsService, ChartOfAccountsService>();
builder.Services.AddScoped<IParamsService, ParamsService>();
builder.Services.AddScoped<ISaleInvoiceService, SaleInvoiceService>();
builder.Services.AddScoped<ISaleInvoiceRepository, SaleInvoiceRepository>();
builder.Services.AddScoped<IQuotationHeaderService, QuotationHeaderService>();
builder.Services.AddScoped<IQuotationDetailService, QuotationDetailService>();
builder.Services.AddScoped<IRequestHeaderService, RequestHeaderService>();
builder.Services.AddScoped<IRequestDetailService, RequestDetailService>();

builder.Services.AddSingleton(typeof(IAppLogger<>), typeof(AppLoggerAdapter<>));

builder.Services.AddHttpContextAccessor();
builder.Services.Configure<CorrelationSettings>(cfg.GetSection("Correlation"));

builder.Services.AddInfrastructure(cfg)
                .AddReportingInfrastructure(cfg);

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "ERP.Api v1"));
}

if (!app.Environment.IsDevelopment())
    app.UseHsts();

if (cfg.GetValue<bool>("Security:RequireHttps"))
    app.UseHttpsRedirection();

app.UseMiddleware<CorrelationIdMiddleware>();
app.UseMiddleware<ExceptionHandlingMiddleware>();
app.UseCors("AllowAll");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.Run();
